import groovy.json.JsonSlurper
import groovy.json.JsonOutput
node {
	def mvnHome
	def artiServer 
	def rtMaven
	def buildInfo
    def gitUrl = 'git@gitlab.com:yongqiang/project-examples.git'
	stage('Prepare') {
		artiServer = Artifactory.server('artiha-demo')
		//artiServer = Artifactory.server('artifactory-test')
		buildInfo = Artifactory.newBuildInfo()
		buildInfo.env.capture = true
		rtMaven = Artifactory.newMavenBuild()
	}
	stage('SCM') {
		git url: 'git@gitlab.com:yongqiang/project-examples.git', credentialsId: 'lyqwaterway'
	}
	//执行maven构建打包
	stage('maven build'){
		rtMaven.resolver server: artiServer, releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot'
		rtMaven.deployer server: artiServer, releaseRepo: 'libs-snapshot-local', snapshotRepo: 'libs-snapshot-local'
		rtMaven.tool = 'maven'
		rtMaven.tool = 'maven'
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install', buildInfo: buildInfo
		artiServer.publishBuildInfo buildInfo

	}
	stage('Sonar') {
		// Sonar scan
        def scannerHome = tool 'sonarClient';
        withSonarQubeEnv('sonar') {
            sh "${scannerHome}/bin/sonar-runner -Dsonar.projectKey=mvn-e2e-pipeline-demo -Dsonar.sources=maven-example/multi3/src"
        }
	}
	//添加sonar扫描结果到包上
	stage("add sonarResult"){
		//获取最新版本号
		def curlstr="curl -uadmin:AKCp5bBXY7TmCE3s13XrGRM3ejcCGfiNgmtAFbaR8yNNLuZW3f7vFhzbv9NxBLP1AWxJr9Zj2 \'http://demo.jfrogchina.com/artifactory/"
		def warverstr= curlstr +  "api/search/latestVersion?g=org.jfrog.test&a=multi3&repos=libs-snapshot-local&v=7.0.1-SNAPSHOT\'";
		echo warverstr
		warVersion = ["bash","-c",warverstr].execute().text
		echo 1 + "    ：  "+warVersion
		//获取sonar扫描结果
		def getSonarIssuesCmd = "curl  GET -v http://47.93.114.82:9000/api/issues/search?componentRoots=${JOB_NAME}";
		process = [ 'bash', '-c', getSonarIssuesCmd].execute().text

		//增加sonar扫描结果到artifactory
		def jsonSlurper = new JsonSlurper()
		def issueMap = jsonSlurper.parseText(process);
		commandText = "curl  -X PUT \"http://demo.jfrogchina.com/artifactory/api/storage/libs-snapshot-local/org/jfrog/test/multi3/7.0.1-SNAPSHOT/multi3-"+warVersion+".war?properties=qulity.gate.sonarUrl=http://47.93.114.82:9000/dashboard/index/${JOB_NAME};qulity.gate.sonarIssue="+issueMap.total+"\" -uadmin:AKCp5bBXY7TmCE3s13XrGRM3ejcCGfiNgmtAFbaR8yNNLuZW3f7vFhzbv9NxBLP1AWxJr9Zj2";
		echo commandText
		process = [ 'bash', '-c', commandText].execute().text
	}
	stage('add jiraResult'){
      def requirements = getRequirementsIds();
      echo "requirements : ${requirements}"
      //def revisionIds = getRevisionIds();
      def revisionIds = "";
      echo "revisionIds : ${revisionIds}"
      commandJira = "curl  -X PUT \"http://demo.jfrogchina.com/artifactory/api/storage/libs-snapshot-local/org/jfrog/test/multi3/7.0.1-SNAPSHOT/multi3-"+warVersion+".war?properties=project.issues="+ requirements +";project.revisionIds="+ revisionIds +"\" -uadmin:AKCp5bBXY7TmCE3s13XrGRM3ejcCGfiNgmtAFbaR8yNNLuZW3f7vFhzbv9NxBLP1AWxJr9Zj2";
	  echo commandJira
	  process = [ 'bash', '-c', commandJira].execute().text
   }
	 //进行测试
	stage('basic test'){
		echo "add test step"
	} 

	stage('xray scan'){
		def xrayConfig = [
          'buildName'     : env.JOB_NAME,
          'buildNumber'   : env.BUILD_NUMBER,
          'failBuild'     : false
        ]
        def xrayResults = artiServer.xrayScan xrayConfig
        echo xrayResults as String
        sleep 10
	}
       
       

	//promotion操作，进行包的升级
	   stage('promotion'){
		def promotionConfig = [
			'buildName'   : buildInfo.name,
			'buildNumber' : buildInfo.number,
			'targetRepo'  : 'libs-release-local',
			'comment': 'this is the promotion comment',
			'sourceRepo':' libs-snapshot-local',
			'status': 'Released',
			'includeDependencies': false,
			'failFast': true,
			'copy': true
		]
		artiServer.promote promotionConfig
	}
	//进行部署
	stage('deploy') {
		def deployCmd = "ansible 127.0.0.1 -m get_url -a 'url=http://demo.jfrogchina.com/artifactory/libs-release-local/org/jfrog/test/multi3/7.0.1-SNAPSHOT/multi3-" + warVersion+ ".war  dest=/home/tomcat/apache-tomcat-8.5.33/webapps/demo.war force=true url_username=admin url_password=AKCp5bBXY7TmCE3s13XrGRM3ejcCGfiNgmtAFbaR8yNNLuZW3f7vFhzbv9NxBLP1AWxJr9Zj2'"
		//sh "ansible 10.1.1.1 -m shell -a '/tomcat/startup.sh' "
		echo deployCmd
		process = [ 'bash', '-c', deployCmd].execute().text
		
		commandText = "curl  -X PUT \"http://demo.jfrogchina.com/artifactory/api/storage/libs-release-local/org/jfrog/test/multi3/7.0.1-SNAPSHOT/multi3-"+warVersion+".war?properties=deploy.tool=ansible;deploy.env=127.0.0.1\" -uadmin:AKCp5bBXY7TmCE3s13XrGRM3ejcCGfiNgmtAFbaR8yNNLuZW3f7vFhzbv9NxBLP1AWxJr9Zj2";
		echo commandText
		[ 'bash', '-c', commandText].execute().text
		
		def stopCmd = "ansible 127.0.0.1 -m shell -a '/home/tomcat/apache-tomcat-8.5.33/bin/shutdown.sh'"
		echo stopCmd
		[ 'bash', '-c', stopCmd].execute().text
		def startCmd = "ansible 127.0.0.1 -m shell -a '/home/tomcat/apache-tomcat-8.5.33/bin/startup.sh'"
		echo startCmd
		[ 'bash', '-c', startCmd].execute().text
	}
}

@NonCPS
def getRequirementsIds(){
    def reqIds = "";
    final changeSets = currentBuild.changeSets
    echo 'changeset count:'+ changeSets.size().toString()
    final changeSetIterator = changeSets.iterator()
    while (changeSetIterator.hasNext()) {
        final changeSet = changeSetIterator.next();
        def logEntryIterator = changeSet.iterator();
        while (logEntryIterator.hasNext()) {
            final logEntry = logEntryIterator.next()
            def patten = ~/#[\w\-_\d]+/;
            def matcher = (logEntry.getMsg() =~ patten);
            def count = matcher.getCount();
            for (int i = 0; i < count; i++){
                reqIds += matcher[i].replace('#', '') + ","
            }
        }
    }
    return reqIds;
}
@NonCPS
 def getRevisionIds(){
    def reqIds = "";
    final changeSets = currentBuild.changeSets
    final changeSetIterator = changeSets.iterator()
    while (changeSetIterator.hasNext()) {
        final changeSet = changeSetIterator.next();
        def logEntryIterator = changeSet.iterator();
        while (logEntryIterator.hasNext()) {
            final logEntry = logEntryIterator.next()
            reqIds += logEntry.getRevision() + ","
        }
    }
    return reqIds
}